### ISSUE TITLE
异步调用合约方法， SendTranscationWithReceiptDecodeAsyncTest()，logs为空，不能解析event

### ISSUE THREAD

**Issue by Taishan-web** [FISCO-BCOS/csharp-sdk#2]
下面的测试代码时：
返回的： receiptResultDto.Logs 是空值：
下面两个校验失败， 获取事件列表为空
Assert.NotEmpty(receiptResultDto.Logs);
var eventList = solidityAbi.EventDecode(eventName, receiptResultDto.Logs);

public async Task SendTranscationWithReceiptDecodeAsyncTest()
        {

          ....
            Assert.NotEmpty(receiptResultDto.Output);
            Assert.NotEmpty(receiptResultDto.Input);
            //Assert.NotEmpty(receiptResultDto.Logs);
            var solidityAbi = new SolidityABI(abi);
          
          ... 
            string eventName = "SetEvent";
            var eventList = solidityAbi.EventDecode(eventName, receiptResultDto.Logs);
         ...

        }

如果使用同步发送交易测试， 没有该问题发生

SendTranscationWithReceiptDecodeTest

**Comment by Taishan-web** [comment]
合约地址错误

**Comment by linbin524** [comment]
是运行测试模式、还是调试测试模式？刚才试了两种都是可以的
